### ISSUE TITLE
你好，能否解释一下random/temporal/structural temporal的区别？

### ISSUE THREAD

**Issue by gw-zhong** [Columbine21/NIAT#1]
在论文中看到，对于模态特征缺失主要有random/temporal/structural temporal三种设置，但是还是不太清楚呢？在您先前的文章TFR-Net中，missing rate对于每个模态来说是相同的，比如missing rate = 0.3，那么text/audio/visual的特征丢失率都是0.3，请问本文的R-MFM也是指这种情况吗？（比如图2(c)中，每个模态都丢失2个特征？）structural temporal可从图4中看到，我的理解是所有模态在连续一段time step上特征都缺失，那么temporal是什么情况呢？是指所有模态在某个time step上特征都缺失，然后这些time step随机分布吗？
还有一个问题就是，对于temporal/structural temporal，既然是所有模态在某个/某些time step上特征都缺失，那是否必须得先进行模态序列对齐？而random是不需要模态序列对齐的吧？

**Comment by Columbine21** [comment]
您好，这个问题在论文的Appendix中有具体解释；（IEEE Trans 的附录在单独的media里面，下图这里。）
<img width="1132" alt="截屏2023-04-21 上午9 51 45" src="https://user-images.githubusercontent.com/46373350/233521957-d4cd1a72-ce95-421d-8204-b4cd5fdb4f9d.png">

我们采用random/temporal/structural temporal的描述是为了与CMU论文 MULTIBENCH: Multiscale Benchmarks for Multimodal Representation Learning 一致。

**Comment by Columbine21** [comment]
Q2：在您先前的文章TFR-Net中，missing rate对于每个模态来说是相同的，比如missing rate = 0.3，那么text/audio/visual的特征丢失率都是0.3，请问本文的R-MFM也是指这种情况吗？
A2：嗯是的，为了能够定量进行测试，文中的缺失率对各个模态是一致的。
Q3: structural temporal可从图4中看到，我的理解是所有模态在连续一段time step上特征都缺失，那么temporal是什么情况呢？是指所有模态在某个time step上特征都缺失，然后这些time step随机分布吗？
A3: 您的理解应该是正确的，具体可以参考 Appendix中的说明。
Q4: 还有一个问题就是，对于temporal/structural temporal，既然是所有模态在某个/某些time step上特征都缺失，那是否必须得先进行模态序列对齐？而random是不需要模态序列对齐的吧？
A4: 嗯，是的，这篇文章考虑的是使用时间对齐的序列特征，与CMU的 MULTIBENCH 一致。包括R-MFM，T-MFM，ST-MFM都是在对齐数据上进行的。

**Comment by gw-zhong** [comment]
好的，非常感谢您及时的解答！
